### PR TITLE
feat(connector): wire easebuzz with two-step seamless flow

### PR DESCRIPTION
**Pull request by kanikac199**
## Summary

- Wire easebuzz connector into the full system infrastructure (proto, domain types, config, dispatch)
- Implement two-step seamless payment flow matching the Haskell `euler-api-txns` reference:
  1. `POST /payment/initiateLink` → get `access_key` (via `CreateOrder` gRPC flow)
  2. `POST /initiate_seamless_payment/` → authorize with `access_key` + payment method data
- Support 5 payment methods: **UPI Collect, UPI Intent, UPI QR, Wallet, Netbanking**
- Support 6 flows: **CreateOrder, Authorize, PSync, Capture, Refund, RSync**

## Test Results

All flows tested end-to-end against easebuzz sandbox via gRPC:

| Payment Method | CreateOrder | Authorize | PSync | Refund | RSync |
|---|---|---|---|---|---|
| UPI Collect | :white_check_mark: | :white_check_mark: PENDING | :white_check_mark: CHARGED | :white_check_mark: REFUND_PENDING | :white_check_mark: REFUND_PENDING |
| UPI Intent | :white_check_mark: | :white_check_mark: PENDING | :white_check_mark: FAILURE (sandbox bounced) | - | - |
| UPI QR | :white_check_mark: | :white_check_mark: PENDING | :white_check_mark: FAILURE (sandbox bounced) | - | - |
| Wallet | :white_check_mark: | :white_check_mark: PENDING | :white_check_mark: PENDING | - | - |
| Netbanking | :white_check_mark: | :white_check_mark: PENDING | :white_check_mark: FAILURE (sandbox bounced) | - | - |

---

<details>
<summary><b>gRPC Test Curls & Responses (click to expand)</b></summary>

### 1. UPI Collect — Full Flow

**1.1 CreateOrder (initiateLink)**
```bash
grpcurl -plaintext \
  -H 'x-connector: easebuzz' -H 'x-auth: body-key' \
  -H 'x-api-key: <EASEBUZZ_API_KEY>' -H 'x-key1: <EASEBUZZ_API_SALT>' \
  -d '{"merchant_order_id":"ebz_uc_01","amount":{"minor_amount":10000,"currency":"INR"},"metadata":{"value":"{\"productinfo\":\"Test\",\"firstname\":\"Test\",\"email\":\"customer@example.com\",\"phone\":\"9999999999\"}"}}' \
  localhost:8000 types.PaymentService/CreateOrder
```
```json
{
  "connectorOrderId": "3c9ebbc22c90921f62001002c946540aef42f77264f19d17932e9a54b8b7a33d",
  "status": "PENDING",
  "statusCode": 200
}
```

**1.2 Authorize (UPI Collect)**
```bash
grpcurl -plaintext \
  -H 'x-connector: easebuzz' -H 'x-auth: body-key' \
  -H 'x-api-key: <EASEBUZZ_API_KEY>' -H 'x-key1: <EASEBUZZ_API_SALT>' \
  -d '{"connector_order_id":"<ACCESS_KEY>","merchant_transaction_id":"ebz_uc_01","amount":{"minor_amount":10000,"currency":"INR"},"payment_method":{"upi_collect":{"vpa_id":{"value":"success@easebuzz"}}},"capture_method":"AUTOMATIC","auth_type":"NO_THREE_DS","return_url":"https://example.com/return","address":{"billing_address":{"first_name":{"value":"Test"},"email":{"value":"customer@example.com"},"phone_number":{"value":"9999999999"}}}}' \
  localhost:8000 types.PaymentService/Authorize
```
```json
{
  "connectorTransactionId": "ebz_uc_01",
  "status": "PENDING",
  "statusCode": 200
}
```

**1.3 PSync**
```bash
grpcurl -plaintext \
  -H 'x-connector: easebuzz' -H 'x-auth: body-key' \
  -H 'x-api-key: <EASEBUZZ_API_KEY>' -H 'x-key1: <EASEBUZZ_API_SALT>' \
  -d '{"connector_transaction_id":"ebz_uc_01","merchant_transaction_id":"ebz_uc_01","amount":{"minor_amount":10000,"currency":"INR"}}' \
  localhost:8000 types.PaymentService/Get
```
```json
{
  "connectorTransactionId": "S260415075DW8N",
  "status": "CHARGED",
  "statusCode": 200,
  "merchantTransactionId": "ebz_uc_01"
}
```

**1.4 Refund (50 INR partial)**
```bash
grpcurl -plaintext \
  -H 'x-connector: easebuzz' -H 'x-auth: body-key' \
  -H 'x-api-key: <EASEBUZZ_API_KEY>' -H 'x-key1: <EASEBUZZ_API_SALT>' \
  -d '{"merchant_refund_id":"ebz_ref_01","connector_transaction_id":"S260415075DW8N","payment_amount":10000,"refund_amount":{"minor_amount":5000,"currency":"INR"}}' \
  localhost:8000 types.PaymentService/Refund
```
```json
{
  "connectorRefundId": "RFXP9UOVXV",
  "status": "REFUND_PENDING",
  "statusCode": 200
}
```

**1.5 RSync**
```bash
grpcurl -plaintext \
  -H 'x-connector: easebuzz' -H 'x-auth: body-key' \
  -H 'x-api-key: <EASEBUZZ_API_KEY>' -H 'x-key1: <EASEBUZZ_API_SALT>' \
  -d '{"refund_id":"RFXP9UOVXV","connector_transaction_id":"S260415075DW8N","merchant_refund_id":"ebz_ref_01"}' \
  localhost:8000 types.RefundService/Get
```
```json
{
  "connectorRefundId": "RFXP9UOVXV",
  "status": "REFUND_PENDING",
  "statusCode": 200
}
```

---

### 2. UPI Intent

**2.1 CreateOrder**
```bash
grpcurl -plaintext \
  -H 'x-connector: easebuzz' -H 'x-auth: body-key' \
  -H 'x-api-key: <EASEBUZZ_API_KEY>' -H 'x-key1: <EASEBUZZ_API_SALT>' \
  -d '{"merchant_order_id":"ebz_ui_01","amount":{"minor_amount":10000,"currency":"INR"},"metadata":{"value":"{\"productinfo\":\"Test\",\"firstname\":\"Test\",\"email\":\"customer@example.com\",\"phone\":\"9999999999\"}"}}' \
  localhost:8000 types.PaymentService/CreateOrder
```
```json
{ "connectorOrderId": "<ACCESS_KEY>", "status": "PENDING", "statusCode": 200 }
```

**2.2 Authorize (UPI Intent)**
```bash
grpcurl -plaintext \
  -H 'x-connector: easebuzz' -H 'x-auth: body-key' \
  -H 'x-api-key: <EASEBUZZ_API_KEY>' -H 'x-key1: <EASEBUZZ_API_SALT>' \
  -d '{"connector_order_id":"<ACCESS_KEY>","merchant_transaction_id":"ebz_ui_01","amount":{"minor_amount":10000,"currency":"INR"},"payment_method":{"upi_intent":{}},"capture_method":"AUTOMATIC","auth_type":"NO_THREE_DS","return_url":"https://example.com/return","address":{"billing_address":{"first_name":{"value":"Test"},"email":{"value":"customer@example.com"},"phone_number":{"value":"9999999999"}}}}' \
  localhost:8000 types.PaymentService/Authorize
```
```json
{ "connectorTransactionId": "ebz_ui_01", "status": "PENDING", "statusCode": 200 }
```

**2.3 PSync**
```json
{ "connectorTransactionId": "S260415075DW8O", "status": "FAILURE", "statusCode": 200 }
```
> Sandbox bounced — no real UPI app to accept intent

---

### 3. UPI QR

**3.1 CreateOrder → 3.2 Authorize**
```bash
# Same pattern as above with: "payment_method":{"upi_qr":{}}
```
```json
{ "connectorTransactionId": "ebz_uq_01", "status": "PENDING", "statusCode": 200 }
```

**3.3 PSync**
```json
{ "connectorTransactionId": "S260415075DW8P", "status": "FAILURE", "statusCode": 200 }
```
> Sandbox bounced — no real QR scan

---

### 4. Wallet (EaseBuzz Redirect)

**4.1 CreateOrder → 4.2 Authorize**
```bash
# Same pattern as above with: "payment_method":{"easebuzz_redirect":{}}
```
```json
{ "connectorTransactionId": "ebz_wl_01", "status": "PENDING", "statusCode": 200 }
```

**4.3 PSync**
```json
{ "connectorTransactionId": "S260415075DW8Q", "status": "PENDING", "statusCode": 200 }
```
> Wallet redirect pending customer action

---

### 5. Netbanking (SBI)

**5.1 CreateOrder → 5.2 Authorize**
```bash
# Same pattern as above with: "payment_method":{"netbanking":{"issuer":"StateBank"}}
```
```json
{ "connectorTransactionId": "ebz_nb_01", "status": "PENDING", "statusCode": 200 }
```

**5.3 PSync**
```json
{ "connectorTransactionId": "S260415075DW90", "status": "FAILURE", "statusCode": 200 }
```
> Sandbox bounced — no real bank login

</details>

---

## Test plan

- [x] `cargo check -p connector-integration` — compiles with no errors or warnings
- [x] `cargo check -p grpc-server` — compiles
- [x] gRPC CreateOrder returns access_key from easebuzz sandbox
- [x] gRPC Authorize sends seamless request with access_key for all 5 payment methods
- [x] gRPC PSync retrieves transaction status with correct hash verification
- [x] gRPC Refund initiates partial refund successfully
- [x] gRPC RSync retrieves refund status from nested refunds array
- [x] PR self-review: all blocking issues (amount format consistency, secret leak, stale docs) fixed

### CODE REVIEW

File: crates/types-traits/grpc-api-types/proto/payment.proto [hunk 1]
```diff
@@ -741,6 +741,7 @@ enum Connector {
   PPRO = 113;
   FISERVCOMMERCEHUB = 114;
   TRUSTLY = 115;
+  EASEBUZZ = 116;
```
Comment (maverox) [inline crates/types-traits/grpc-api-types/proto/payment.proto]: 🔴 **Critical: Proto field number conflict with PR #795 (pinelabs_online)**

This PR assigns `EASEBUZZ = 116` in the Connector enum and `easebuzz = 116` in the ConnectorSpecificConfig oneof. PR #795 (pinelabs_online) also assigns `PINELABS_ONLINE = 116` and `pinelabs_online = 116`.

If both PRs merge, there will be a protobuf compilation error (duplicate field numbers in the same enum/oneof).

**Fix:** Coordinate with the author of PR #795 to assign non-conflicting field numbers. One connector should use 116 and the other 117 (or another unused number).

File: crates/integrations/connector-integration/src/connectors/easebuzz.rs [hunk 2]
```diff
@@ -0,0 +1,1148 @@
+pub mod transformers;
```
Comment (maverox) [inline crates/integrations/connector-integration/src/connectors/easebuzz.rs:1]: 🟡 **`get_currency_unit` returns `Minor` but `amount_converter` is `StringMajorUnit`**

The connector uses `amount_converter: StringMajorUnit` in the prerequisites macro, meaning amounts are converted from minor to major units for API requests. However, `get_currency_unit()` returns `CurrencyUnit::Minor`.

Other connectors that use `StringMajorUnit` (e.g., rapyd, braintree, fiservemea, noon, aci) return `CurrencyUnit::Base`. The mismatch means the framework may double-convert or mis-handle amounts.

**Fix:** Change `get_currency_unit()` to return `CurrencyUnit::Base` to match the `StringMajorUnit` converter, consistent with other connectors that send amounts in major units.

File: crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs [hunk 3]
```diff
@@ -0,0 +1,1417 @@
...
+    router_response_types::RedirectForm,
+};
+use error_stack::ResultExt;
+use hyperswitch_masking::{PeekInterface, Secret};
+use serde::{Deserialize, Serialize};
+
+use crate::{connectors::easebuzz::EasebuzzRouterData, types::ResponseRouterData};
+
+/// Extract the inner string from a `StringMajorUnit` for use in hash computation.
+fn string_major_unit_to_string(amount: &StringMajorUnit) -> String {
```
Comment (maverox) [inline crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs:25]: 🟡 **`string_major_unit_to_string` may return empty string for integer amounts**

The function serializes `StringMajorUnit` to JSON, then tries to extract a string value via `.as_str()`. If `serde_json::to_value` produces a `Number` (e.g., `10000` instead of `"10000"`), `.as_str()` returns `None`, and `unwrap_or_default()` returns `""`.

An empty amount string in the hash computation will produce an incorrect hash, causing the Easebuzz API to reject the request with an authentication error.

**Fix:** Use `.to_string()` on the `Value` directly, or better yet, access the inner string from `StringMajorUnit` directly rather than going through JSON serialization.

File: crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs [hunk 4]
```diff
@@ -0,0 +1,1417 @@
...
+    }
+}
+
+// ============================================================================
+// InitiateLink Types (Step 1 — get access_key)
+// ============================================================================
+
+/// Compute SHA-512 hash for initiateLink request.
+/// Formula: SHA512(key|txnid|amount|productinfo|firstname|email|udf1|udf2|...|udf10|salt)
+pub fn compute_initiate_link_hash(
```
Comment (maverox) [inline crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs:100]: 🟡 **Hash computation exposes API salt in function signature**

`compute_initiate_link_hash` takes `salt` as a `&str` parameter. While this is necessary for the hash computation, the salt is passed around as a plain string after `.peek().to_string()`. If any logging or error reporting captures the function arguments, the salt could leak.

This is a minor concern since the salt is only in memory briefly, but consider whether the function could accept `&Secret<String>` and call `.peek()` internally to minimize the exposure window.

File: crates/internal/integration-tests/src/connector_specs/easebuzz/specs.json [hunk 5]
```diff
@@ -0,0 +1,10 @@
+{
+  "connector": "easebuzz",
+  "supported_suites": [
```
Comment (maverox) [inline crates/internal/integration-tests/src/connector_specs/easebuzz/specs.json:3]: 🔴 **Missing `create_order` in supported_suites**

The Easebuzz connector implements a two-step flow: `CreateOrder` (initiateLink → access_key) then `Authorize` (seamless payment). `EasebuzzPaymentsRequest::try_from` hard-requires `connector_order_id` (the access_key from CreateOrder).

Without `create_order` in the spec, the test harness cannot produce a valid `connector_order_id` for the authorize step, so the `authorize` suite will fail on missing `connector_order_id`.

**Fix:** Add `"create_order"` to `supported_suites` so the harness runs CreateOrder first and feeds the returned `connector_order_id` into Authorize.

File: crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs [hunk 6]
```diff
@@ -0,0 +1,1414 @@
...
+                    additional_context: Some(
+                        "Failed to convert capture amount for Easebuzz".to_string(),
+                    ),
+                    ..Default::default()
+                },
+            })?;
+        let amount_for_hash = string_major_unit_to_string(&amount);
+
+        let key_str = auth.api_key.peek().to_string();
+        let salt_str = auth.api_salt.peek().to_string();
```
Comment (maverox) [inline crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs]: 🟡 **`api_salt` materialized to plain `String` via `.peek().to_string()`**

The `compute_initiate_link_hash` was fixed to accept `&Secret<String>`, but the capture, refund, PSync, and RSync hash helpers still receive the salt as a bare `&str` after `.peek().to_string()`. If any logging or error reporting captures function arguments, the salt could leak.

Apply the same `&Secret<String>` pattern used for `compute_initiate_link_hash` to `compute_easebuzz_capture_hash`, `compute_easebuzz_refund_hash`, `compute_easebuzz_sync_hash`, and `compute_easebuzz_refund_sync_hash`.

File: docs-generated/connectors/easebuzz.md [hunk 7]
```diff
@@ -0,0 +1,162 @@
...
+
+```javascript
+const { ConnectorClient } = require('connector-service-node-ffi');
+
+// Reuse this client for all flows
+const client = new ConnectorClient({
+    connector: 'Easebuzz',
+    environment: 'sandbox',
+    connector_auth_type: {
+        header_key: { api_key: 'YOUR_API_KEY' },
```
Comment (maverox) [inline docs-generated/connectors/easebuzz.md:48]: 🟡 **Generated docs show `header_key/api_key` auth but proto uses `EasebuzzConfig { api_key, api_salt }`**

The JavaScript snippet shows `connector_auth_type: { header_key: { api_key } }`, but `payment.proto` defines `EasebuzzConfig` with both `api_key` and `api_salt`. The Kotlin (line 66) and Rust (line 84) snippets have the same mismatch. The Python snippet (line 28) only shows `EasebuzzConfig(api_key=...)` without `api_salt`.

These docs will mislead integrators. Regenerate from a source that emits both `api_key` and `api_salt`.

**Review by maverox — COMMENTED** [review]
## Review Summary

### Verdict: ✅ Approve with Comments

**Classification:** Connector New Integration + Proto/API Contract Change

---

### ✅ Positive Findings

1. **Complete connector infrastructure wiring** - All registration points present:
   - `connectors.rs` module declaration ✅
   - `ConnectorEnum` variant ✅
   - Config TOML files (dev/sandbox/prod) ✅
   - Proto definitions and SDK regeneration ✅

2. **Correct hash implementation** - SHA-512 formula matches Easebuzz specification:
   ```
   SHA512(key|txnid|amount|productinfo|firstname|email|udf1|...|udf10|salt)
   ```

3. **Proper two-step flow implementation** - CreateOrder (`initiateLink`) → Authorize (`initiate_seamless_payment`) matches the Haskell `euler-api-txns` reference.

4. **Amount unit handling** - Correct use of `StringMajorUnit` for Easebuzz (expects base units, not minor).

5. **Smart response preprocessing** - Handling HTML responses from seamless endpoint by wrapping as `"null"` JSON is pragmatic.

---

### 📝 Non-Blocking Observations

**Observation 1: Error response consistency**
Some error responses return `attempt_status: None` while others return `Some(enums::AttemptStatus::Failure)`. Consider standardizing on `Some(Failure)` for error cases.

**Observation 2: Secondary base URL requirement**
The PSync, Refund, and RSync flows require `secondary_base_url` (dashboard URL). The error message is clear, but consider if there's a way to fall back to primary URL if dashboard is unavailable.

**Observation 3: Missing newline at EOF**
`data/field_probe/easebuzz.json` is missing a trailing newline (shown in diff as `\ No newline at end of file`).

---

### 🔍 Mixed PR Analysis

This PR spans multiple scenarios:
- **Connector New Integration** (primary)
- **Proto/API Contract Change** (payment.proto additions)
- **SDK/FFI Codegen** (JS SDK updates)

The generated files appear properly synchronized with source changes. The `EasebuzzConfig` in proto maps correctly to `connector_specific_config::Config::Easebuzz` in the generated Rust code.

---

### 📊 Test Evidence Review

Full flow testing documented in PR:
- UPI Collect: CreateOrder → Authorize → PSync → Refund → RSync ✅
- UPI Intent/QR: End-to-end tested ✅
- Wallet: Pending status confirmed ✅
- Netbanking: End-to-end tested ✅

Hash verification in responses confirms proper implementation.

---

Well-structured new connector implementation following established patterns.

File: crates/integrations/connector-integration/src/connectors/easebuzz.rs [hunk 8]
```diff
@@ -0,0 +1,1148 @@
...
+{
+    fn get_supported_payment_methods(&self) -> Option<&'static SupportedPaymentMethods> {
+        Some(&EASEBUZZ_SUPPORTED_PAYMENT_METHODS)
+    }
+
+    fn get_supported_webhook_flows(&self) -> Option<&'static [enums::EventClass]> {
+        None
+    }
+
+    fn get_connector_about(&self) -> Option<&'static ConnectorInfo> {
```
Comment (maverox) [inline crates/integrations/connector-integration/src/connectors/easebuzz.rs]: 🟡 [S2] New connector without test coverage: Easebuzz is a new connector integration. Verify that:

1. Integration tests exist and pass with sandbox credentials
2. field_probe coverage reflects the actual supported flows
3. The 5 supported flows (authorize, psync, capture, refund, rsync) are tested end-to-end

Consider adding explicit test verification steps before merging this PR.

File: crates/integrations/connector-integration/src/connectors/easebuzz.rs [hunk 9]
```diff
@@ -0,0 +1,1148 @@
...
+        PaymentsResponseData,
+    > for Easebuzz<T>
+{
+}
+
+impl<T: PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize>
+    ConnectorIntegrationV2<
+        IncrementalAuthorization,
+        PaymentFlowData,
+        PaymentsIncrementalAuthorizationData,
```
Comment (maverox) [inline crates/integrations/connector-integration/src/connectors/easebuzz.rs]: 🟢 [S3] Hash-based auth in request body: Easebuzz uses hash-based auth in the request body rather than headers. This is documented correctly with `get_auth_header` returning an empty vec. Consider adding a comment explaining the hash algorithm used for security auditing.

**Review by maverox — DISMISSED** [review]

**Review by maverox — DISMISSED** [review]

**Review by Jeeva0104 — COMMENTED** [review]
## Code Review Findings

### S1 (Major) Blockers

#### 1. `..Default::default()` used in error context instead of detailed diagnostics
Using `Default::default()` in error context hides diagnostic information needed for debugging. Please include `http_status_code` where available.

**Files affected:**
- `transformers.rs:463-467`
- `transformers.rs:609`  
- `transformers.rs:881`
- `transformers.rs:950`
- `easebuzz.rs:516-518`

**Suggested fix:**
```rust
context: errors::ResponseTransformationErrorContext {
    http_status_code: Some(res.status_code),
    additional_context: Some("...".to_string()),
}
```

#### 2. `attempt_status: None` in RSync and Refund error responses
Per project standards, `attempt_status` should distinguish between integration errors (pending) and connector-declared failures (failed). Setting `None` loses this distinction.

**Files affected:**
- `easebuzz.rs:1069` (RSync error response)
- `easebuzz.rs:1153` (Refund error response)
- `transformers.rs:2632` (Refund sync error)

**Suggested fix:**
- Use `Some(AttemptStatus::Failure)` for explicit connector errors
- Use `Some(AttemptStatus::Pending)` for integration/network errors

---

### S2 (Moderate) Non-blocking

#### 1. Missing `http_status_code` in some `change_context` calls
Including http_status_code in ResponseTransformationErrorContext aids debugging and monitoring.

**Files affected:**
- `easebuzz.rs:511-520` (build_error_response)
- `transformers.rs:1400` (initiateLink error)

#### 2. Hard-coded default values for email/phone
Using `"customer@example.com"` and `"9999999999"` as defaults may cause confusion in production.

**Files affected:**
- `transformers.rs:1425-1426`
- `transformers.rs:2347-2354`

**Suggestion:** Consider making these explicitly required or using clearer placeholder conventions.

---

### S3 (Minor) Nits

#### 1. Inconsistent hash computation documentation
The comment says `udf1..udf10` are empty but the format string structure could be clearer.

**File:** `transformers.rs:1311-1332`

**Suggestion:** Clarify that the formula includes 10 empty UDF fields between email and salt.

---

### Summary

**Verdict:** `comment` - Address S1 findings before merge

**Positive aspects:**
- Complete connector implementation with all 6 flows
- Good use of macros for boilerplate reduction
- Proper secret handling with `Secret<String>`
- Comprehensive test coverage and documentation
- All companion files present (specs, field_probe, examples)

File: crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs [hunk 10]
```diff
@@ -0,0 +1,1431 @@
...
+impl<T: PaymentMethodDataTypes + std::fmt::Debug + Sync + Send + 'static + Serialize>
+    TryFrom<
+        EasebuzzRouterData<
+            RouterDataV2<Capture, PaymentFlowData, PaymentsCaptureData, PaymentsResponseData>,
+            T,
+        >,
+    > for EasebuzzCaptureRequest
+{
+    type Error = error_stack::Report<IntegrationError>;
+
```
Comment (Jeeva0104) [inline crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs:630]: Don't use `..Default::default()` in error context. Provide explicit `http_status_code` for debugging.

File: crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs [hunk 11]
```diff
@@ -0,0 +1,1431 @@
...
+    ) -> Result<Self, Self::Error> {
+        let router_data = &item.router_data;
+        let auth = EasebuzzAuthType::try_from(&router_data.connector_config).change_context(
+            IntegrationError::FailedToObtainAuthType {
+                context: errors::IntegrationErrorContext {
+                    additional_context: Some(
+                        "Easebuzz requires api_key and api_salt in ConnectorSpecificConfig"
+                            .to_string(),
+                    ),
+                    ..Default::default()
```
Comment (Jeeva0104) [inline crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs]: Don't use `..Default::default()` in error context. Include `http_status_code` when available.

File: crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs [hunk 12]
```diff
@@ -0,0 +1,1431 @@
...
+
+impl TryFrom<ResponseRouterData<EasebuzzRefundResponse, Self>>
+    for RouterDataV2<Refund, RefundFlowData, RefundsData, RefundsResponseData>
+{
+    type Error = error_stack::Report<errors::ConnectorError>;
+
+    fn try_from(
+        item: ResponseRouterData<EasebuzzRefundResponse, Self>,
+    ) -> Result<Self, Self::Error> {
+        let response = &item.response;
```
Comment (Jeeva0104) [inline crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs:989]: Don't use `..Default::default()` in error context. Provide explicit `http_status_code` for debugging.

File: crates/integrations/connector-integration/src/connectors/easebuzz.rs [hunk 13]
```diff
@@ -0,0 +1,1148 @@
...
+    curl_request: FormUrlEncoded(EasebuzzPaymentsRequest),
+    curl_response: EasebuzzPaymentsResponse,
+    flow_name: Authorize,
+    resource_common_data: PaymentFlowData,
+    flow_request: PaymentsAuthorizeData<T>,
+    flow_response: PaymentsResponseData,
+    http_method: Post,
+    preprocess_response: true,
+    generic_type: T,
+    [PaymentMethodDataTypes + Debug + Sync + Send + 'static + Serialize],
```
Comment (Jeeva0104) [inline crates/integrations/connector-integration/src/connectors/easebuzz.rs:519]: Don't use `..Default::default()` in error context. Use explicit `http_status_code` and descriptive `additional_context`.

File: crates/integrations/connector-integration/src/connectors/easebuzz.rs [hunk 14]
```diff
@@ -0,0 +1,1148 @@
...
+                    context: errors::IntegrationErrorContext {
+                        additional_context: Some(
+                            "Easebuzz requires secondary_base_url (dashboard URL) for PSync and Refund flows".to_string()
+                        ),
+                        ..Default::default()
+                    },
+                })
+                .map_err(error_stack::Report::from)?;
+            Ok(format!("{secondary_base_url}/transaction/v2/refund"))
+        }
```
Comment (Jeeva0104) [inline crates/integrations/connector-integration/src/connectors/easebuzz.rs:1078]: `attempt_status: None` loses distinction between integration errors and connector failures. Use `Some(AttemptStatus::Failure)` for explicit errors or `Some(AttemptStatus::Pending)` for integration issues.

File: crates/integrations/connector-integration/src/connectors/easebuzz.rs [hunk 15]
```diff
@@ -0,0 +1,1148 @@
...
+            _req: &RouterDataV2<Authorize, PaymentFlowData, PaymentsAuthorizeData<T>, PaymentsResponseData>,
+        ) -> CustomResult<Vec<(String, Maskable<String>)>, IntegrationError> {
+            Ok(vec![(
+                headers::CONTENT_TYPE.to_string(),
+                "application/x-www-form-urlencoded".to_string().into(),
+            )])
+        }
+
+        fn get_url(
+            &self,
```
Comment (Jeeva0104) [inline crates/integrations/connector-integration/src/connectors/easebuzz.rs:532]: S1: `attempt_status: None` loses distinction between integration errors and connector-declared failures. Use `Some(AttemptStatus::Failure)` for explicit errors or `Some(AttemptStatus::Pending)` for integration/network issues.

File: crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs [hunk 16]
```diff
@@ -0,0 +1,1431 @@
...
+            Some(obj) => obj,
+            None => {
+                let txn_id = router_data
+                    .resource_common_data
+                    .connector_request_reference_id
+                    .clone();
+                return Ok(Self {
+                    response: Ok(PaymentsResponseData::TransactionResponse {
+                        resource_id: ResponseId::ConnectorTransactionId(txn_id),
+                        redirection_data: None,
```
Comment (Jeeva0104) [inline crates/integrations/connector-integration/src/connectors/easebuzz/transformers.rs:487]: S1: Don't use `..Default::default()` in error context. Include explicit `http_status_code` and descriptive `additional_context` for debugging.

**Review by JeevaRamu0104 — DISMISSED** [review]

**Review by maverox — APPROVED** [review]

**Review by JeevaRamu0104 — APPROVED** [review]
